/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algprog2proje2;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ozgen
 */
public class NewJFrame extends javax.swing.JFrame {

    DoublyLinkedList dll = new DoublyLinkedList();
    DefaultListModel dlm = new DefaultListModel();

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        ekle = new javax.swing.JButton();
        bilgileriGetir = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        azSirala = new javax.swing.JButton();
        zaSirala = new javax.swing.JButton();
        cikis = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Ad Soyad:");

        jLabel2.setText("Doğum Tarihi:");

        jLabel3.setText("Klüpler:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        bilgileriGetir.setText("Bilgileri Getir");
        bilgileriGetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgileriGetirActionPerformed(evt);
            }
        });

        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        azSirala.setText("A-Z Sırala");
        azSirala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azSiralaActionPerformed(evt);
            }
        });

        zaSirala.setText("Z-A Sırala");
        zaSirala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zaSiralaActionPerformed(evt);
            }
        });

        cikis.setText("Çıkış");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addComponent(ekle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bilgileriGetir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(azSirala, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zaSirala, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bilgileriGetir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ekle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(azSirala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zaSirala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cikis)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        String ayir[], ayir2[];
        int sayac = 0;
        if (jTextField1.getText().equals("") || jTextField2.getText().equals("") || jTextArea1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bilgiler boş bırakılamaz.");
        } else {
            //Ad soyada göre verileri eklemek
            Bilgi yeni = new Bilgi(jTextField1.getText(), jTextField2.getText());
            for (int i = 0; i < dll.getLength(); i++) {
                ayir = dll.getItem(i).split(", ");
                ayir2 = jTextField1.getText().split(" ");
                if (ayir[0].compareToIgnoreCase(jTextField1.getText()) > 0) {

                } else if (ayir[0].compareToIgnoreCase(jTextField1.getText()) < 0) {
                    sayac++;
                } else if (ayir[0].compareToIgnoreCase(jTextField1.getText()) == 0) {

                    String bilgi = dll.getItem(i);
                    String bol[] = bilgi.split("\\[|, |\\]|\\.");
                    Bilgi yeni2 = new Bilgi(bol[0], bol[1]);
                    dll.deleteToIndex(sayac + 1);
                    dll.insertToIndex(yeni2, sayac);
                    for (int j = 2; j < bol.length; j++) {
                        if (!bol[j].equals("")) {
                            yeni2.klupler.add(bol[j]);
                        }
                    }
                    yeni2.klupler.add(jTextArea1.getText());
                    sayac = -1;
                }
            }
            if (sayac == 0) {
                dll.insertToStart(yeni);
                yeni.klupler.add(jTextArea1.getText());
            } else if (sayac == dll.getLength()) {
                dll.insertToIndex(yeni, sayac);
                yeni.klupler.add(jTextArea1.getText());
            } else if (sayac > 0) {
                dll.insertToIndex(yeni, sayac);
                yeni.klupler.add(jTextArea1.getText());
            }
        }
        doldur();
        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_ekleActionPerformed

    private void bilgileriGetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgileriGetirActionPerformed
        //adı ve soyadı girilen sporcunun bilgilerini yazdırıyor
        //bilgileri girilen kayıt yok ise mesaj veriyor.
        String kelime;
        String ayir[];
        int say = 0;
        if (jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Aranan futbolcunun adı ve soyadı boş bırakılamaz");
            say++;
        } else {
            kelime = jTextField1.getText();
            for (int i = 0; i < dll.getLength(); i++) {
                ayir = dll.getItem(i).split(", ");

                if (ayir[0].equalsIgnoreCase(kelime)) {
                    dlm.clear();
                    dlm.addElement(dll.getItem(i));
                    say++;
                    i = dll.getLength();
                }
            }
            if (say == 0) {
                JOptionPane.showMessageDialog(null, jTextField1.getText() + " Ad Soyadına sahip kayıt bulunamadı");
            }
            jList1.setModel(dlm);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextArea1.setText("");
        }
    }//GEN-LAST:event_bilgileriGetirActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        //adı ve soyadı girilen sporcu listede var iste listeden siliyor
        //bilgileri girilen kayıt yok ise mesaj veriyor.
        String kelime;
        String ayir[];
        int sayac = 0;

        if (jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Kaydı silinecek sporcunun adı ve soyadı boş bırakılamaz.");
        } else {

            for (int i = 0; i < dll.getLength(); i++) {
                ayir = dll.getItem(i).split(", ");

                kelime = jTextField1.getText();

                if (ayir[0].equalsIgnoreCase(kelime)) {

                    dll.deleteToIndex(i + 1);
                    sayac++;
                }
            }
            if (sayac == 0) {
                JOptionPane.showMessageDialog(null, jTextField1.getText() + "Ad Soyadına sahip kayıt bulunamadı.");
            }

        }
        //jList1.setModel(dlm);
        doldur();
        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_silActionPerformed

    private void azSiralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azSiralaActionPerformed
        //JListe linked listi a-z sıralı olarak yazdırıyor. 
        dlm.clear();
        for (int i = 0; i < dll.getLength(); i++) {
            dlm.addElement(dll.getItem(i));
        }
        jList1.setModel(dlm);
    }//GEN-LAST:event_azSiralaActionPerformed

    private void zaSiralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zaSiralaActionPerformed
        //JListe linked listi z-a sıralı olarak yazdırıyor.
        dlm.clear();
        for (int i = dll.getLength() - 1; i >= 0; i--) {
            dlm.addElement(dll.getItem(i));
        }
        jList1.setModel(dlm);
    }//GEN-LAST:event_zaSiralaActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        //cikis butonuna basıldığında linked list içindeki veriler dosyaya yazdırılıyor
        String filename = "C:\\Users\\ozgen\\Documents\\NetBeansProjects\\AlgProg2Proje2\\src\\algprog2proje2\\sporcu.txt";
        try {
            PrintWriter output = new PrintWriter(filename);
            output.println("");
            for (int i = 0; i < dll.getLength(); i++) {
                output.println(dll.getItem(i));
            }
            output.close();

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Kaydedilemedi!");
        }
        System.exit(0);
    }//GEN-LAST:event_cikisActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int satir = 0;
        String str, isim;
        String ayir[];
        try {
            FileReader words = new FileReader("C:\\Users\\ozgen\\Documents\\NetBeansProjects\\AlgProg2Proje2\\src\\algprog2proje2\\sporcu.txt");
            FileReader words2 = new FileReader("C:\\Users\\ozgen\\Documents\\NetBeansProjects\\AlgProg2Proje2\\src\\algprog2proje2\\sporcu.txt");
            try (BufferedReader reader = new BufferedReader(words)) {
                str = reader.readLine();

                while (str != null) {
                    satir++;
                    str = reader.readLine();
                }
            }
            try (BufferedReader reader2 = new BufferedReader(words2)) {
                reader2.readLine();
                for (int j = 0; j < satir - 1; j++) {
                    isim = reader2.readLine();

                    ayir = isim.split(", ");
                    Bilgi yeni = new Bilgi(ayir[0], ayir[1]);
                    dll.insertToEnd(yeni);
                    for (int i = 2; i < ayir.length; i++) {
                        yeni.klupler.add(ayir[i]);
                    }
                }
                doldur();
            }

        } catch (IOException e) {

            JOptionPane.showMessageDialog(null, "Dosya Okunamadı.");
        }
    }//GEN-LAST:event_formWindowOpened

    void doldur() {
        //Jliste linked list'in içindeki verileri ekliyor.
        dlm.clear();
        for (int i = 0; i < dll.getLength(); i++) {
            dlm.addElement(dll.getItem(i));
        }
        jList1.setModel(dlm);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton azSirala;
    private javax.swing.JButton bilgileriGetir;
    private javax.swing.JButton cikis;
    private javax.swing.JButton ekle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton sil;
    private javax.swing.JButton zaSirala;
    // End of variables declaration//GEN-END:variables
}
